// Shared state to capture password reset URLs generated by Better Auth
// when triggered as part of the invite flow (vs a user-initiated reset)
const pending = new Map<string, (url: string) => void>();

export function registerInviteCapture(email: string): Promise<string> {
  return new Promise((resolve) => {
    pending.set(email, resolve);
  });
}

export function resolveInviteCapture(email: string, url: string): boolean {
  const resolve = pending.get(email);
  if (!resolve) return false;
  pending.delete(email);
  resolve(url);
  return true;
}
